// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiparisTakipSistemi.Models;

#nullable disable

namespace SiparisTakipSistemi.Migrations
{
    [DbContext(typeof(SiparisTakipDbContext))]
    [Migration("20250623234753_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiparisTakipSistemi.Models.KargoFirmalari", b =>
                {
                    b.Property<int>("KargoFirmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KargoFirmaID"));

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KargoFirmaID");

                    b.ToTable("KargoFirmalari");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Kargolar", b =>
                {
                    b.Property<int>("KargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KargoID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KargoFirmaID")
                        .HasColumnType("int");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("TahminiTeslimGun")
                        .HasColumnType("int");

                    b.Property<string>("TakipNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KargoID")
                        .HasName("PK__Kargolar__8E5A959B36615701");

                    b.HasIndex("KargoFirmaID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Kargolar", (string)null);
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KullaniciID")
                        .HasName("PK__Kullanic__E011F09BF005D59A");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.SiparisDetaylari", b =>
                {
                    b.Property<int>("DetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetayID"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<decimal>("Toplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DetayID")
                        .HasName("PK__SiparisD__8E8164A5A741476F");

                    b.HasIndex("SiparisID");

                    b.ToTable("SiparisDetaylari", (string)null);
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Siparisler", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"));

                    b.Property<int>("KargoID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("SiparisID")
                        .HasName("PK__Siparisl__C3F03BDD9675DC02");

                    b.HasIndex("KargoID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Siparisler", (string)null);
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Kargolar", b =>
                {
                    b.HasOne("SiparisTakipSistemi.Models.KargoFirmalari", "KargoFirmasi")
                        .WithMany("Kargolar")
                        .HasForeignKey("KargoFirmaID")
                        .HasConstraintName("FK_Kargolar_KargoFirmalari");

                    b.HasOne("SiparisTakipSistemi.Models.Kullanicilar", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KargoFirmasi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.SiparisDetaylari", b =>
                {
                    b.HasOne("SiparisTakipSistemi.Models.Siparisler", "Siparis")
                        .WithMany("SiparisDetaylaris")
                        .HasForeignKey("SiparisID")
                        .IsRequired()
                        .HasConstraintName("FK__SiparisDe__Sipar__412EB0B6");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Siparisler", b =>
                {
                    b.HasOne("SiparisTakipSistemi.Models.Kargolar", "Kargo")
                        .WithMany("Siparisler")
                        .HasForeignKey("KargoID")
                        .IsRequired()
                        .HasConstraintName("FK__Siparisle__Kargo__3E52440B");

                    b.HasOne("SiparisTakipSistemi.Models.Kullanicilar", "Kullanici")
                        .WithMany("Siparislers")
                        .HasForeignKey("KullaniciID")
                        .IsRequired()
                        .HasConstraintName("FK__Siparisle__Kulla__3D5E1FD2");

                    b.Navigation("Kargo");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.KargoFirmalari", b =>
                {
                    b.Navigation("Kargolar");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Kargolar", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Kullanicilar", b =>
                {
                    b.Navigation("Siparislers");
                });

            modelBuilder.Entity("SiparisTakipSistemi.Models.Siparisler", b =>
                {
                    b.Navigation("SiparisDetaylaris");
                });
#pragma warning restore 612, 618
        }
    }
}
